# Debug Prediction Configuration - Session-Based
# ===============================================
# Configuration for debugging and development testing
# Uses training session for exact feature reproduction

# Training session directory (contains model + exact config + results)
training_session: "training_sessions/session_20250817_024332_Aggressive_Maximum_Performance_v1"

prediction:
  temperature: 1.0                   # No temperature scaling for raw predictions
  input_file: "debug_inputs/predict_lyric.txt"  # Single debug location
  output_dir: "prediction_results/debug"
  quiet: false                       # Verbose output for debugging

device: "cpu"  # Force CPU for consistent debugging

config_version: "2.0"
description: "Debug session-based configuration - exact training reproduction"
note: "Features automatically loaded from training_session/training_config_snapshot.yaml for exact debugging"