# Production Prediction Configuration - Session-Based
# ===================================================
# Optimized for AI-less machines and automated deployment
# Uses training session for guaranteed compatibility

# Training session directory (contains model + exact config + results)
training_session: "training_sessions/session_20250817_203021_training_robust_enhanced_boundary_f1_v1"

prediction:
  temperature: 0.6                # Slightly conservative for production
  input_file: "prediction_results/predict_lyric.txt"  # Single production location
  output_dir: "prediction_results"
  quiet: false                      # Silent operation for production

device: "auto"

config_version: "3.0"  
description: "Production session-based configuration - zero drift, maximum reliability"
note: "Features automatically loaded from training_session/training_config_snapshot.yaml"
