batch_size: 24
cosine_t0: 10
cosine_t_max: 100
cosine_t_mult: 2
default_temperature: 0.6
device: mps
dropout: 0.2
emergency_conf95_ratio: 0.8
emergency_f1_threshold: 0.03
emergency_monitoring_enabled: true
emergency_overconf_threshold: 0.96
entropy_lambda: 0.05
experiment_description: Training configuration with composite validation strategy
experiment_name: training_validation_composite_v1
experiment_notes: Training configuration with composite validation strategy. Uses
  WindowDiff and Pk metrics for text segmentation evaluation. Enhanced monitoring
  of segment-level performance and transition accuracy. Optimized for structural coherence
  in predictions.
experiment_tags:
- validation-focused
- segmentation-metrics
- enhanced-monitoring
- production-ready
gradient_clip_norm: 0.4
head_ssm_dimension: 12
head_ssm_enabled: true
head_ssm_words: 2
hidden_dim: 256
label_smoothing: 0.2
learning_rate: 0.0008
lr_factor: 0.5
lr_patience: 6
max_chorus_rate: 0.8
max_conf_over_95_ratio: 0.1
max_confidence_threshold: 0.9
max_epochs: 100
min_chorus_rate: 0.08
min_lr: 1e-6
num_classes: 2
num_workers: 0
output_base_dir: training_sessions
patience: 12
phonetic_ssm_dimension: 12
phonetic_ssm_enabled: true
phonetic_ssm_high_sim_threshold: 0.35
phonetic_ssm_mode: rhyme
phonetic_ssm_normalize: false
phonetic_ssm_normalize_method: zscore
phonetic_ssm_similarity_method: binary
pos_ssm_dimension: 12
pos_ssm_enabled: true
pos_ssm_high_sim_threshold: 0.28
pos_ssm_similarity_method: combined
pos_ssm_tagset: simplified
print_batch_every: 10
save_best_model: true
save_final_model: true
save_training_metrics: true
scheduler: cosine
seed: 42
skip_batches: 30
skip_epochs: 3
step_gamma: 0.5
step_size: 25
string_ssm_case_sensitive: false
string_ssm_dimension: 12
string_ssm_enabled: true
string_ssm_remove_punctuation: true
string_ssm_similarity_method: word_overlap
string_ssm_similarity_threshold: 0.08
tail_ssm_dimension: 12
tail_ssm_enabled: true
tail_ssm_words: 2
temperature_grid:
- 0.4
- 0.6
- 0.8
- 1.0
- 1.2
- 1.5
- 1.8
- 2.2
- 2.5
test_file: data/test.jsonl
train_file: data/train.jsonl
val_f1_collapse_threshold: 0.08
val_file: data/val.jsonl
val_overconf_threshold: 0.95
validation_strategy: composite
warmup_epochs: 5
weight_decay: 0.008
weighted_sampling: true
