anti_collapse: !!python/object:segmodel.utils.config_loader.AntiCollapseConfig
  weighted_sampling: false
attention_dim: null
attention_dropout: 0.1
attention_enabled: false
attention_heads: 4
attention_type: self
batch_size: 64
boundary_temperature: 2.0
calibration_enabled: true
calibration_methods:
- temperature
- platt
cnn_batch_multiplier: 1.0193625999805915
cnn_dilation_rates:
- 1
- 2
- 4
cnn_kernel_sizes:
- 3
- 5
cnn_use_residual: true
cnn_weight_decay: 0.02427036543348163
contextual_enabled: false
contextual_high_sim_threshold: 0.72
contextual_mode: complete
contextual_model: all-MiniLM-L6-v2
contextual_normalize: true
contextual_similarity_metric: cosine
cosine_t0: 10
cosine_t_max: 15
cosine_t_mult: 2
device: mps
dropout: 0.389890856885326
emergency_conf95_ratio: 0.65
emergency_f1_threshold: 0.05
emergency_monitoring_enabled: true
emergency_overconf_threshold: 0.94
experiment_description: BiLSTM training experiment
experiment_name: blstm_experiment
experiment_notes: ''
experiment_tags: []
gradient_clip_norm: 0.33631374206890585
head_ssm_dimension: 12
head_ssm_enabled: false
head_ssm_words: 3
hidden_dim: 128
layer_dropout: 0.17460384611585128
learning_rate: 0.0005475270056465761
line_syllable_ssm_dimension: 12
line_syllable_ssm_enabled: false
line_syllable_ssm_normalize: false
line_syllable_ssm_normalize_method: minmax
line_syllable_ssm_ratio_threshold: 0.1
line_syllable_ssm_similarity_method: cosine
loss:
  boundary_weight: 2.185217598713194
  conf_penalty_lambda: 0.005079892948847538
  conf_threshold: 0.9205971386437602
  entropy_lambda: 0.038569650638799746
  label_smoothing: 0.163428209540776
  segment_consistency_lambda: 0.017178535838363374
  type: boundary_aware_cross_entropy
  use_boundary_as_primary: true
loss_config: !!python/object:segmodel.utils.config_loader.LossConfig
  boundary_weight: 1.0
  conf_penalty_lambda: 0.01
  conf_threshold: 0.7
  entropy_lambda: 0.05
  label_smoothing: 0.0
  loss_type: CrossEntropyWithLabelSmoothing
  segment_consistency_lambda: 0.0
  use_boundary_as_primary: false
lr_factor: 0.3
lr_patience: 2
max_chorus_rate: 0.8591608720134989
max_conf_over_95_ratio: 0.06248767404009699
max_confidence_threshold: 0.9115077839148343
max_epochs: 15
max_seq_length: 1000
min_chorus_rate: 0.05743045948781317
min_delta: 0.000467721140557429
min_lr: 1.0e-06
num_classes: 2
num_layers: 2
num_workers: 0
output_base_dir: results
patience: 4
phonetic_ssm_dimension: 12
phonetic_ssm_enabled: false
phonetic_ssm_high_sim_threshold: 0.30341153033374024
phonetic_ssm_mode: combined
phonetic_ssm_normalize: true
phonetic_ssm_normalize_method: zscore
phonetic_ssm_similarity_method: binary
pos_ssm_dimension: 12
pos_ssm_enabled: false
pos_ssm_high_sim_threshold: 0.25343360871841286
pos_ssm_similarity_method: combined
pos_ssm_tagset: penn
positional_encoding: true
print_batch_every: 10
save_best_model: true
save_final_model: true
save_training_metrics: true
scheduler: onecycle
seed: 42
skip_batches: 15
skip_epochs: 2
step_gamma: 0.5
step_size: 0
string_ssm_case_sensitive: false
string_ssm_dimension: 12
string_ssm_enabled: true
string_ssm_remove_punctuation: true
string_ssm_similarity_method: jaccard
string_ssm_similarity_threshold: 0.04576144614525185
syllable_pattern_ssm_cosine_weight: 0.3
syllable_pattern_ssm_dimension: 12
syllable_pattern_ssm_enabled: true
syllable_pattern_ssm_levenshtein_weight: 0.7
syllable_pattern_ssm_normalize: false
syllable_pattern_ssm_normalize_method: zscore
syllable_pattern_ssm_similarity_method: cosine
tail_ssm_dimension: 12
tail_ssm_enabled: true
tail_ssm_words: 3
test_file: data/test.jsonl
train_file: data/train.jsonl
val_f1_collapse_threshold: 0.1
val_file: data/val.jsonl
val_overconf_threshold: 0.92
validation_strategy: line_f1
warmup_epochs: 5
weight_decay: 0.02427036543348163
weighted_sampling: true
window_size: 7
word2vec_enabled: true
word2vec_high_sim_threshold: 0.82
word2vec_mode: complete
word2vec_model: word2vec-google-news-300
word2vec_normalize: true
word2vec_similarity_metric: cosine
