# Fast Debug BiLSTM Config
# Minimal dimensions for faster iterations & debugging

# Data
data:
  train_file: "data/train.jsonl"
  val_file: "data/val.jsonl"
  test_file: "data/test.jsonl"

# Model
model:
  hidden_dim: 64        
  num_layers: 1
  layer_dropout: 0.25
  num_classes: 2
  dropout: 0.15

  # Attention
  attention_enabled: false
  attention_heads: 2     # Very light
  attention_dropout: 0.10
  attention_dim: 64      # Match hidden_dim
  positional_encoding: false  # Disabled for speed
  max_seq_length: 512    # Shorter cap

# Training
training:
  batch_size: 16         # Smaller batch fits everywhere
  learning_rate: 0.001   # Higher LR for quick convergence
  weight_decay: 0.01
  max_epochs: 8          # Only a few epochs for debug
  patience: 3
  gradient_clip_norm: 0.5

  scheduler: "cosine"
  min_lr: 1e-5
  cosine_t_max: 8

# Anti-Collapse
anti_collapse:
  label_smoothing: 0.1
  weighted_sampling: false  # Skip for debug
  entropy_lambda: 0.05

# Emergency Monitoring
emergency_monitoring:
  enabled: false  # Skip expensive monitoring for debug

# Calibration
calibration:
  enabled: false  # Skip calibration in debug
  methods: []

# Validation
validation_strategy: "line_f1"

# Features (keep minimal SSMs for debugging)
features:
  head_ssm:
    enabled: false
    dimension: 12
    head_words: 2

  tail_ssm:
    enabled: false
    dimension: 12
    tail_words: 2

  phonetic_ssm:
    enabled: true
    dimension: 4     # Downscaled
    mode: "rhyme"
    similarity_method: "binary"
    normalize: false
    high_sim_threshold: 0.35
  
  pos_ssm:
    enabled: false
    dimension: 4
    tagset: "simplified"
    similarity_method: "combined"
  
  string_ssm:
    enabled: true
    dimension: 4
    case_sensitive: false
    remove_punctuation: true
    similarity_threshold: 0.1
    similarity_method: "word_overlap"

# Embeddings (summary only)
embeddings:
  word2vec:
    enabled: false
    model: "word2vec-google-news-300"
    mode: "summary"        # only 12D
    normalize: false
    similarity_metric: "cosine"
    high_sim_threshold: 0.8

  contextual:
    enabled: false
    model: "all-MiniLM-L6-v2"
    mode: "summary"        # only 12D
    normalize: false
    similarity_metric: "cosine"
    high_sim_threshold: 0.7

# Output
output:
  base_dir: "training_sessions_debug"
  save_best_model: false
  save_final_model: false
  save_training_metrics: true
  save_config_snapshot: false

# System
system:
  seed: 42
  device: "auto"
  num_workers: 2
  deterministic: true

# Experiment
experiment:
  name: "debug_fast"
  description: "Tiny config for fast debugging (1-layer, summary embeddings)"
  tags: ["debug", "fast", "light"]
  notes: "Minimal capacity, just for pipeline testing"
