# ============================================================================
# ABLATION STUDY - String SSM Focus
# Test String SSM with optimized thresholds as primary feature
# Understanding feature contribution to performance
# ============================================================================

# Data paths
data:
  train_file: "data/train.jsonl"
  val_file: "data/val.jsonl"
  test_file: "data/test.jsonl"

# Model architecture - smaller for single feature focus
model:
  hidden_dim: 128        # Standard size for ablation
  num_classes: 2
  dropout: 0.3

# Training parameters - focused training
training:
  batch_size: 16
  learning_rate: 0.001
  weight_decay: 0.01
  max_epochs: 60
  patience: 10
  gradient_clip_norm: 1.0

# Anti-collapse settings
anti_collapse:
  label_smoothing: 0.2
  weighted_sampling: true
  entropy_lambda: 0.0

# Emergency monitoring
emergency_monitoring:
  enabled: true
  max_confidence_threshold: 0.95
  min_chorus_rate: 0.05
  max_chorus_rate: 0.85
  max_conf_over_95_ratio: 0.8

# Features configuration - STRING SSM + HEAD/TAIL for comparison
features:
  head_ssm:
    enabled: true          # Keep for baseline comparison
    output_dim: 12
    head_words: 2
  tail_ssm:
    enabled: true          # Keep for baseline comparison
    output_dim: 12
    tail_words: 2
  phonetic_ssm:
    enabled: false         # 🔍 DISABLED for ablation
  pos_ssm:
    enabled: false         # 🔍 DISABLED for ablation
  string_ssm:
    enabled: true          # 🔍 MAIN FOCUS with optimized threshold
    output_dim: 12
    case_sensitive: false
    remove_punctuation: true
    similarity_threshold: 0.15  # 🚀 OPTIMIZED - lower than baseline 0.3
    similarity_method: "word_overlap"

# Output settings
output:
  base_dir: "training_sessions"
  save_best_model: true
  save_final_model: true
  save_training_metrics: true

# System settings
system:
  seed: 42
  device: "auto"
  num_workers: 2

# Experiment metadata
experiment:
  name: "Ablation_String_SSM_Focus_v1"
  description: "Test String SSM contribution with head/tail baseline, optimized threshold"
  tags: ["ablation", "string_ssm_focus", "feature_analysis", "optimized_threshold"]
  notes: "Isolate String SSM impact: head+tail+string vs full feature set, threshold=0.15"
