# ============================================================================
# CONSERVATIVE CONFIGURATION - Safe incremental improvements
# Safer improvements from baseline with measured risk
# Expected: Chorus F1 0.75-0.78, Macro F1 0.82-0.85
# Training time: 20-25 minutes  
# ============================================================================

# Data paths
data:
  train_file: "data/train.jsonl"
  val_file: "data/val.jsonl"
  test_file: "data/test.jsonl"

# Model architecture - MODERATE CAPACITY INCREASE
model:
  hidden_dim: 192        # 游리 MODERATE 50% increase from 128
  num_classes: 2
  dropout: 0.35          # 游리 SMALL reduction from 0.4

# Training parameters - MODEST IMPROVEMENTS
training:
  batch_size: 16
  learning_rate: 0.001
  weight_decay: 0.01
  max_epochs: 65         # 游리 MODEST increase from 55  
  patience: 10           # 游리 SLIGHTLY more patient than 8
  gradient_clip_norm: 1.0

# Anti-collapse settings - keep stable
anti_collapse:
  label_smoothing: 0.2
  weighted_sampling: true
  entropy_lambda: 0.0

# Emergency monitoring - conservative limits
emergency_monitoring:
  enabled: true
  max_confidence_threshold: 0.95  # Keep current limit
  min_chorus_rate: 0.05
  max_chorus_rate: 0.85
  max_conf_over_95_ratio: 0.8

# Features configuration - MODEST THRESHOLD REDUCTIONS
features:
  head_ssm:
    enabled: true
    output_dim: 12
    head_words: 2
  tail_ssm:
    enabled: true
    output_dim: 12
    tail_words: 2
  phonetic_ssm:
    enabled: true
    output_dim: 12
    mode: "rhyme"
    similarity_method: "binary"
    normalize: false
    normalize_method: "zscore"
    high_sim_threshold: 0.7  # 游리 MODEST reduction from 0.8
  pos_ssm:
    enabled: true
    output_dim: 12
    tagset: "simplified"
    similarity_method: "combined"
    high_sim_threshold: 0.6  # 游리 MODEST reduction from 0.7
  string_ssm:
    enabled: true
    output_dim: 12
    case_sensitive: false
    remove_punctuation: true
    similarity_threshold: 0.25  # 游리 SMALL reduction from 0.3
    similarity_method: "word_overlap"

# Output settings
output:
  base_dir: "training_sessions"
  save_best_model: true
  save_final_model: true
  save_training_metrics: true

# System settings
system:
  seed: 42
  device: "auto"
  num_workers: 2

# Experiment metadata
experiment:
  name: "Conservative_Safe_Improvement_v1"
  description: "Safe incremental improvements with modest threshold reductions"
  tags: ["conservative", "incremental", "safe_improvement", "modest_thresholds"]
  notes: "Conservative approach: 50% capacity increase, modest threshold reductions, safe training"
