# Quick Test Configuration
# For rapid development and debugging

# Dataset Configuration
data:
  train_file: "data/train.jsonl"
  val_file: "data/val.jsonl" 
  test_file: "data/test.jsonl"
  
# Model Architecture (smaller for quick testing)
model:
  hidden_dim: 64  # Reduced for speed
  num_classes: 2
  dropout: 0.3
  
# Training Parameters (short run)
training:
  batch_size: 8   # Smaller batch
  learning_rate: 0.002  # Slightly higher LR
  weight_decay: 0.01
  max_epochs: 5   # Very short run
  patience: 3
  gradient_clip_norm: 1.0
  
# Anti-Collapse Configuration
anti_collapse:
  label_smoothing: 0.15  # Slightly less smoothing
  weighted_sampling: true
  entropy_lambda: 0.0
  
# Emergency Monitoring (more tolerant for testing)
emergency_monitoring:
  enabled: false  # Disabled for debugging
  max_confidence_threshold: 0.98
  min_chorus_rate: 0.01
  max_chorus_rate: 0.95
  
# Features
features:
  head_ssm:
    enabled: true
    output_dim: 12
    head_words: 2
  tail_ssm:
    enabled: true
    output_dim: 12
    tail_words: 2
  phonetic_ssm:
    enabled: true
    output_dim: 12
    mode: "rhyme"
    similarity_method: "edit_distance"
    normalize: true
    normalize_method: "zscore"
    high_sim_threshold: 0.8
  pos_ssm:
    enabled: false
    output_dim: 12
    tagset: "universal"
    similarity_method: "lcs"
    high_sim_threshold: 0.7
    
# Output
output:
  base_dir: "training_sessions"
  save_best_model: true
  save_final_model: false  # Skip final model for quick tests
  
# System
system:
  seed: 42
  device: "auto"
  
# Experiment
experiment:
  name: "quick_test"
  description: "Quick test run for development and debugging"
  tags: ["test", "debug", "quick"]
