# Test configuration for String SSM feature
# This config enables all features including the new String SSM

# Data paths - using the same as the baseline
data:
  train_file: "data/train.jsonl"
  val_file: "data/val.jsonl"
  test_file: "data/test.jsonl"

# Model architecture
model:
  hidden_dim: 128
  num_classes: 2
  dropout: 0.4

# Training parameters - quick test settings
training:
  batch_size: 16
  learning_rate: 0.001
  weight_decay: 0.01
  max_epochs: 55
  patience: 8
  gradient_clip_norm: 1.0

# Anti-collapse settings
anti_collapse:
  label_smoothing: 0.2
  weighted_sampling: true
  entropy_lambda: 0.0

# Emergency monitoring
emergency_monitoring:
  enabled: true
  max_confidence_threshold: 0.95
  min_chorus_rate: 0.05
  max_chorus_rate: 0.85
  max_conf_over_95_ratio: 0.8

# Features configuration - enable all features including String SSM
features:
  head_ssm:
    enabled: true
    output_dim: 12
    head_words: 2
  tail_ssm:
    enabled: true
    output_dim: 12
    tail_words: 2
  phonetic_ssm:
    enabled: true  # Disable to avoid CMU dict dependency issues
    output_dim: 12
    mode: "rhyme"
    similarity_method: "binary"
    normalize: false
    normalize_method: "zscore"
    high_sim_threshold: 0.8
  pos_ssm:
    enabled: true  # Disable to avoid NLP library dependency issues
    output_dim: 12
    tagset: "simplified"
    similarity_method: "combined"
    high_sim_threshold: 0.7
  string_ssm:
    enabled: true
    output_dim: 12
    case_sensitive: false
    remove_punctuation: true
    similarity_threshold: 0.3  # Use threshold to focus on higher similarities
    similarity_method: "word_overlap"  # Fast method for training

# Output settings
output:
  base_dir: "training_sessions"
  save_best_model: true
  save_final_model: true
  save_training_metrics: true

# System settings
system:
  seed: 42
  device: "auto"
  num_workers: 2

# Experiment metadata
experiment:
  name: "SSM, head_ssm, tail_ssm, string_ssm 55 epochs"
  description: "Testing SSM, head_ssm, tail_ssm, string_ssm"
  tags: ["SSM", "head_ssm", "tail_ssm", "string_ssm", "test", "baseline"]
  notes: "Verify SSM, head_ssm, tail_ssm, string_ssm feature works in full training pipeline"
