batch_size: 32
cosine_t0: 10
cosine_t_max: 100
cosine_t_mult: 2
default_temperature: 1.0
device: mps
dropout: 0.3
emergency_conf95_ratio: 0.8
emergency_f1_threshold: 0.05
emergency_monitoring_enabled: true
emergency_overconf_threshold: 0.98
entropy_lambda: 0.05
experiment_description: Optimized BiLSTM with 5-feature ensemble, LR scheduling, and
  temperature calibration
experiment_name: blstm_optimized_v2
experiment_notes: 'Updated configuration with all performance improvements: larger
  batch size, better features, LR scheduling'
experiment_tags:
- optimized
- 5-features
- lr-scheduling
- temperature-calibration
gradient_clip_norm: 1.0
head_ssm_dimension: 12
head_ssm_enabled: true
head_ssm_words: 2
hidden_dim: 512
label_smoothing: 0.15
learning_rate: 0.001
lr_factor: 0.5
lr_patience: 8
max_chorus_rate: 0.75
max_conf_over_95_ratio: 0.6
max_confidence_threshold: 0.9
max_epochs: 100
min_chorus_rate: 0.08
min_lr: 1.0e-05
num_classes: 2
num_workers: 4
output_base_dir: training_sessions
patience: 15
phonetic_ssm_dimension: 12
phonetic_ssm_enabled: true
phonetic_ssm_high_sim_threshold: 0.4
phonetic_ssm_mode: rhyme
phonetic_ssm_normalize: true
phonetic_ssm_normalize_method: zscore
phonetic_ssm_similarity_method: binary
pos_ssm_dimension: 12
pos_ssm_enabled: true
pos_ssm_high_sim_threshold: 0.3
pos_ssm_similarity_method: combined
pos_ssm_tagset: simplified
print_batch_every: 10
save_best_model: true
save_final_model: true
save_training_metrics: true
scheduler: plateau
seed: 42
skip_batches: 50
skip_epochs: 3
step_gamma: 0.5
step_size: 25
string_ssm_case_sensitive: false
string_ssm_dimension: 12
string_ssm_enabled: true
string_ssm_remove_punctuation: true
string_ssm_similarity_method: word_overlap
string_ssm_similarity_threshold: 0.1
tail_ssm_dimension: 12
tail_ssm_enabled: true
tail_ssm_words: 2
temperature_grid:
- 0.5
- 0.8
- 1.0
- 1.2
- 1.5
- 2.0
- 3.0
test_file: data/test.jsonl
train_file: data/train.jsonl
val_f1_collapse_threshold: 0.1
val_file: data/val.jsonl
val_overconf_threshold: 0.96
warmup_epochs: 5
weight_decay: 0.01
weighted_sampling: true
