batch_size: 16
cosine_t0: 10
cosine_t_max: 60
cosine_t_mult: 2
default_temperature: 1.0
device: mps
dropout: 0.4
emergency_conf95_ratio: 0.8
emergency_f1_threshold: 0.05
emergency_monitoring_enabled: true
emergency_overconf_threshold: 0.98
entropy_lambda: 0.0
experiment_description: BiLSTM baseline with Head-SSM features and anti-collapse measures
experiment_name: blstm_baseline_v1
experiment_notes: Initial baseline experiment with improved loss function
experiment_tags:
- baseline
- head_ssm
- anti_collapse
gradient_clip_norm: 1.0
head_ssm_dimension: 12
head_ssm_enabled: true
head_ssm_words: 2
hidden_dim: 128
label_smoothing: 0.2
learning_rate: 0.001
lr_factor: 0.5
lr_patience: 4
max_chorus_rate: 0.85
max_conf_over_95_ratio: 0.8
max_confidence_threshold: 0.95
max_epochs: 60
min_chorus_rate: 0.05
min_lr: 1e-6
num_classes: 2
num_workers: 0
output_base_dir: training_sessions
patience: 8
phonetic_ssm_dimension: 12
phonetic_ssm_enabled: true
phonetic_ssm_high_sim_threshold: 0.8
phonetic_ssm_mode: rhyme
phonetic_ssm_normalize: true
phonetic_ssm_normalize_method: zscore
phonetic_ssm_similarity_method: edit_distance
pos_ssm_dimension: 12
pos_ssm_enabled: true
pos_ssm_high_sim_threshold: 0.7
pos_ssm_similarity_method: lcs
pos_ssm_tagset: universal
print_batch_every: 10
save_best_model: true
save_final_model: true
save_training_metrics: true
scheduler: plateau
seed: 42
skip_batches: 50
skip_epochs: 3
step_gamma: 0.5
step_size: 15
string_ssm_case_sensitive: false
string_ssm_dimension: 12
string_ssm_enabled: true
string_ssm_remove_punctuation: true
string_ssm_similarity_method: word_overlap
string_ssm_similarity_threshold: 0.0
tail_ssm_dimension: 12
tail_ssm_enabled: true
tail_ssm_words: 2
temperature_grid:
- 0.6
- 0.8
- 1.0
- 1.2
- 1.5
- 1.7
- 2.0
test_file: data/test.jsonl
train_file: data/train.jsonl
val_f1_collapse_threshold: 0.1
val_file: data/val.jsonl
val_overconf_threshold: 0.96
validation_strategy: line_f1
warmup_epochs: 5
weight_decay: 0.01
weighted_sampling: true
