batch_size: 16
device: mps
dropout: 0.4
emergency_monitoring_enabled: true
entropy_lambda: 0.0
experiment_description: BiLSTM baseline with Head-SSM features and anti-collapse measures
experiment_name: blstm_baseline_v1
experiment_notes: Initial baseline experiment with improved loss function
experiment_tags:
- baseline
- head_ssm
- anti_collapse
gradient_clip_norm: 1.0
head_ssm_dimension: 12
head_ssm_enabled: true
hidden_dim: 128
label_smoothing: 0.2
learning_rate: 0.001
max_chorus_rate: 0.85
max_conf_over_95_ratio: 0.8
max_confidence_threshold: 0.95
max_epochs: 60
min_chorus_rate: 0.05
num_classes: 2
num_workers: 4
output_base_dir: training_sessions
patience: 8
phonetic_ssm_dimension: 12
phonetic_ssm_enabled: true
phonetic_ssm_high_sim_threshold: 0.8
phonetic_ssm_mode: rhyme
phonetic_ssm_normalize: true
phonetic_ssm_normalize_method: zscore
phonetic_ssm_similarity_method: edit_distance
pos_ssm_dimension: 12
pos_ssm_enabled: true
pos_ssm_high_sim_threshold: 0.7
pos_ssm_similarity_method: lcs
pos_ssm_tagset: universal
save_best_model: true
save_final_model: true
save_training_metrics: true
seed: 42
tail_ssm_dimension: 12
tail_ssm_enabled: true
test_file: data/test.jsonl
train_file: data/train.jsonl
val_file: data/val.jsonl
weight_decay: 0.01
weighted_sampling: true
