batch_size: 8
default_temperature: 1.0
device: mps
dropout: 0.2
emergency_conf95_ratio: 0.8
emergency_f1_threshold: 0.05
emergency_monitoring_enabled: true
emergency_overconf_threshold: 0.98
entropy_lambda: 0.0
experiment_description: Maximum performance config with very low thresholds and large
  model
experiment_name: Aggressive_Maximum_Performance_v1
experiment_notes: 'Push performance limits: 512D model, very low SSM thresholds, long
  patient training'
experiment_tags:
- aggressive
- max_capacity
- very_low_thresholds
- long_training
gradient_clip_norm: 0.5
head_ssm_dimension: 12
head_ssm_enabled: true
head_ssm_words: 3
hidden_dim: 512
label_smoothing: 0.15
learning_rate: 0.0005
max_chorus_rate: 0.85
max_conf_over_95_ratio: 0.9
max_confidence_threshold: 0.97
max_epochs: 120
min_chorus_rate: 0.05
num_classes: 2
num_workers: 0
output_base_dir: training_sessions
patience: 20
phonetic_ssm_dimension: 12
phonetic_ssm_enabled: true
phonetic_ssm_high_sim_threshold: 0.4
phonetic_ssm_mode: rhyme
phonetic_ssm_normalize: false
phonetic_ssm_normalize_method: zscore
phonetic_ssm_similarity_method: binary
pos_ssm_dimension: 12
pos_ssm_enabled: true
pos_ssm_high_sim_threshold: 0.3
pos_ssm_similarity_method: combined
pos_ssm_tagset: simplified
save_best_model: true
save_final_model: true
save_training_metrics: true
scheduler: plateau
seed: 42
string_ssm_case_sensitive: false
string_ssm_dimension: 12
string_ssm_enabled: true
string_ssm_remove_punctuation: true
string_ssm_similarity_method: word_overlap
string_ssm_similarity_threshold: 0.1
tail_ssm_dimension: 12
tail_ssm_enabled: true
tail_ssm_words: 3
temperature_grid:
- 0.6
- 0.8
- 1.0
- 1.2
- 1.5
- 1.7
- 2.0
test_file: data/test.jsonl
train_file: data/train.jsonl
val_file: data/val.jsonl
validation_strategy: line_f1
weight_decay: 0.005
weighted_sampling: true
